name: C++ Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up cache for CMake FetchContent
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: cmake-cache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          cmake-cache-${{ runner.os }}-

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build Project
      run: cmake --build build

    - name: Run tests
      working-directory: build
      run: ctest --verbose

    - name: Run App
      run: ./build/FinanceApp
